# Copyright (c), The Rusoil Software Development Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# author : Konstantin Ustiuzhanin
# date   : 2026-Oct-4
# ==============================================================================
"""SQLAlchemy ORM models for the durable store.

These are the tables behind `doc/vision.md` > "Data Model", and the reason the
`alembic/` directory exists:

* :class:`DetectionResult` - one recognised object in one frame.
* :class:`SystemMetadata`  - system-level state, counters and configuration.

Conventions (`doc/conventions.md`):

* ``snake_case`` tables and columns, so the schema can be read from ``psql``
  without a translation layer.
* Every constraint and index is named explicitly through the naming convention
  below. PostgreSQL invents names otherwise, and an autogenerated migration
  cannot later drop a constraint whose name it did not choose.
* Anything filtered or ordered on is a real indexed column; free-form payloads
  go in JSONB so adding a key does not need a migration.
* Timestamps are ``timestamptz`` and UTC. A naive timestamp in an industrial log
  is a bug waiting to happen.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    Float,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = [
    "Base",
    "DetectionResult",
    "ENUM_TYPE_NAMES",
    "ObjectType",
    "SystemMetadata",
    "SystemState",
]

#: Constraint/index naming convention. `alembic revision --autogenerate` derives
#: stable names from this, which is what makes a generated migration reviewable
#: and its `downgrade()` correct.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        identifier = getattr(self, "id", None) or getattr(self, "key", None)
        return f"<{type(self).__name__} {identifier}>"


class ObjectType(str, enum.Enum):
    """What the vision service looks for in the workspace.

    The values match the strings the inference path already emits in
    `src/vision/service.py` (``"metal_sheet"``, ``"debris"``) and the enum named
    in `doc/vision.md`.
    """

    METAL_SHEET = "metal_sheet"
    DETAIL = "detail"
    DEBRIS = "debris"
    CLUTTER = "clutter"


class SystemState(str, enum.Enum):
    """Camera/stream health reported through ``system_metadata``.

    The failure states named in `doc/vision.md` ("Failure Handling") -
    ``NO_TARGET``, ``OUT_OF_REACH``, ``HUMAN_ON_SITE`` - are *detection*
    outcomes rather than stream health, so they belong in a detection's
    ``metadata`` payload and not in this enum.
    """

    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
    ERROR = "error"


def _enum(enum_class: type[enum.Enum], name: str) -> Enum:
    """Build a PostgreSQL ``ENUM`` that stores the member *values*.

    SQLAlchemy's ``Enum`` writes the member *name* by default, so
    ``ObjectType.METAL_SHEET`` would be persisted as ``'METAL_SHEET'`` while
    `src/camera/schemas.py` and `src/vision/service.py` emit ``"metal_sheet"``.
    The database would then hold a vocabulary no other part of the system uses.
    ``values_callable`` pins the labels to the enum values instead.

    ``validate_strings=True`` makes an out-of-vocabulary value fail in Python
    rather than at the database, which is a clearer error for a domain that
    reports specific failure states (``COMM_ERROR``).
    """
    return Enum(
        enum_class,
        name=name,
        native_enum=True,
        validate_strings=True,
        values_callable=lambda cls: [member.value for member in cls],
    )


#: Native PostgreSQL enum types declared by these models, in the order the
#: initial migration creates them.
#:
#: PostgreSQL has no ``CREATE TYPE ... IF NOT EXISTS``, so a downgrade that does
#: not drop these leaves them behind and the next upgrade fails with
#: ``type "object_type" already exists``. `alembic/env.py` extends Alembic's
#: ``DropTableOp`` renderer to emit the matching ``DROP TYPE IF EXISTS``; this
#: tuple documents the vocabulary and is asserted against the model metadata by
#: `tests/db/test_models.py`.
ENUM_TYPE_NAMES: tuple[str, ...] = ("object_type", "camera_status")


class DetectionResult(Base):
    """One detected object in one frame.

    Coordinates are normalised to ``[0, 1]`` relative to the frame, exactly as
    `src/camera/schemas.py::DetectionResult` produces them. Conversion to
    millimetres happens through
    `src/vision/constants.py::SCALE_FACTOR_MM_PER_UNIT` (the documented 3000 mm
    camera height) and is deliberately not persisted, so a recalibration does not
    invalidate history.
    """

    __tablename__ = "detection_results"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="Surrogate key, generated application-side so a row can be logged "
        "before the INSERT is flushed.",
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
        doc="UTC time of the frame that produced the detection. Server-defaulted "
        "as well, so a manually inserted row is still valid.",
    )
    frame_id: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Sequential frame counter from the camera service. Not unique: two "
        "objects in one frame share it.",
    )
    object_type: Mapped[ObjectType] = mapped_column(
        _enum(ObjectType, "object_type"),
        nullable=False,
        index=True,
        doc="Classification result.",
    )
    coordinates: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        doc="Normalised bounding box: {x, y, width, height}, each in [0, 1].",
    )
    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="Model confidence in [0, 1].",
    )
    detection_metadata: Mapped[Optional[dict[str, Any]]] = mapped_column(
        "metadata",
        JSONB,
        nullable=True,
        doc="Free-form extras: model version, inference latency, workspace state "
        "such as NO_TARGET / OUT_OF_REACH / HUMAN_ON_SITE. Stored as `metadata` "
        "and named `detection_metadata` on the class because `metadata` is "
        "reserved by SQLAlchemy's declarative API.",
    )

    __table_args__ = (
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="confidence_range"),
        CheckConstraint("frame_id >= 0", name="frame_id_non_negative"),
        # The two documented access patterns: time-range history and per-type
        # history ("last 30 days of metal_sheet").
        Index("ix_detection_results_type_timestamp", "object_type", "timestamp"),
    )


class SystemMetadata(Base):
    """System-level state, counters and the live configuration snapshot.

    Key/value rather than one column per field: the documented attributes
    (``camera_status``, ``processing_fps``, ``last_heartbeat``,
    ``configuration``) are only a starting set, and adding a metric on an
    industrial line must not require a schema migration. The values that are
    actually queried or graphed are promoted to their own indexed columns
    alongside the payload.
    """

    __tablename__ = "system_metadata"

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    key: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        doc="Stable identifier, e.g. `camera_status` or `processing_fps`.",
    )
    value: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Scalar value as text, so a status or a version does not need JSON "
        "quoting.",
    )
    value_json: Mapped[Optional[dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
        doc="Structured form, for values that are not scalar (the "
        "`configuration` snapshot).",
    )
    camera_status: Mapped[Optional[SystemState]] = mapped_column(
        _enum(SystemState, "camera_status"),
        nullable=True,
        index=True,
        doc="Promoted from `value` when `key = 'camera_status'`, so stream health "
        "can be filtered without parsing text.",
    )
    processing_fps: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        doc="Promoted from `value` when `key = 'processing_fps'`. The 60 FPS "
        "target in doc/vision.md is measured against this.",
    )
    last_heartbeat: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
        doc="Last time the system reported in. A stale heartbeat is the primary "
        "`COMM_ERROR` signal.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        doc="Last write to this row, maintained by the database.",
    )

    __table_args__ = (
        UniqueConstraint("key", name="key"),
        CheckConstraint(
            "processing_fps IS NULL OR processing_fps >= 0",
            name="processing_fps_non_negative",
        ),
    )
