from enum import StrEnum


class ErrorCode(StrEnum):
    MODEL_NOT_LOADED = "INFERENCE__MODEL_NOT_LOADED"
    INVALID_INPUT_SHAPE = "INFERENCE__INVALID_INPUT_SHAPE"
    INFERENCE_FAILED = "INFERENCE__INFERENCE_FAILED"
    BATCH_TOO_LARGE = "INFERENCE__BATCH_TOO_LARGE"